<?php include 'header.php' ?>

<h1>A Journey into Transcendentalism -Introduction</h1>

<h2 id="purpose">Purpose</h2>
<p>The goal of this project was to apply Transcendentalist principles into our own life to gain a better understanding of the philosopy. After reading texts such as "Self Reliance" by Ralph Waldo Emerson and much of <i>Walden</i> by Henry David Thoreau, we created personal, modern versions of Transcendentalism.</p>

<h2 id="principles">Principles embodied</h2>
<p>For four days, I had two goals: (1) to spend time photographing nature, and (2) to meditate every day. I took photos around my house, and I took care to pick up on smaller details that would otherwise be overlooked. In this way, I would appreciate both the "leafless root" and the "full-blown flower" (Emerson).</p>

<h2 id="before">Before</h2>
<p>Before this project, I felt that I already practiced aspects of Transcendentalism, such as non-conformity and introspection. However, I didn't spend that much time outside, and I didn't slow my life down enough.</p>

<h2 id="inspiration">Inspiration</h2>
<iframe width="420" height="315" src="http://www.youtube.com/embed/UhXiHJ8vfuk" frameborder="0" allowfullscreen></iframe>
<br><br>
<p>The TED Talk above inspired me to slow down my life, and to stop rushing everything I did. In addition, a nature walk and journaling activity showed me how fast my thoughts fly by - I realized that I needed to change something in order to slow myself down. So, I decided to meditate every day using the Headspace app, which would let me slow down and spend more time alone.</p>
<p>In addition, I was amazed at how much beauty and peace Thoreau found in nature. I don't spend that much time outside, especially with New England weather, but I decided to try and discover that beauty around me through photography.</p>

<div class="panel panel-default" id="book-connections">
    <div class="panel-body">
        <h3>Inspiration from Thoreau and Emerson</h3>
        <span class="glyphicon glyphicon-plus"></span>
        <span class="glyphicon glyphicon-minus hidden"></span>
        <div id="book-connections-content">
            <div class="analysis-block">
                <div class="panel panel-default quote">
                    <div class="panel-body">
                        "Still we live meanly, like ants; though the fable tells us that we were long ago changed into men; like pygmies we fight with cranes; it is error upon error, and clout upon clout, and our best virtue has for its occasion a superfluous and evitable wretchedness. Our life is frittered away by detail. An honest man has hardly need to count more than his ten fingers, or in extreme cases he may add his ten toes, and lump the rest. Simplicity, simplicity, simplicity! I say, let your affairs be as two or three, and not a hundred or a thousand; instead of a million count half a dozen, and keep your accounts on your thumb-nail. In the midst of this chopping sea of civilized life, such are the clouds and storms and quicksands and thousand-and-one items to be allowed for, that a man has to live, if he would not founder and go to the bottom and not make his port at all, by dead reckoning, and he must be a great calculator indeed who succeeds. Simplify, simplify. Instead of three meals a day, if it be necessary eat but one; instead of a hundred dishes, five; and reduce other things in proportion. Our life is like a German Confederacy, made up of petty states, with its boundary forever fluctuating, so that even a German cannot tell you how it is bounded at any moment." -Thoreau
                    </div>
                </div>
                <p>In this passage from Walden, Thoreau uses repetition, juxtaposition, and metaphors to emphasize the benefits of simplifying one's life, an important principle of Transcendentalism. Repetition is used at the beginning when Thoreau describes a life full of unnecessary complications, calling it "error upon error, and clout upon clout" (59). The repetition of "error" and "clout" imply that these negative consequences appear continuously, and so a complex life can never be free. Repetition is also used later as Thoreau advocates for "simplicity, simplicity, simplicity," which complements the aforementioned repetition (59). Here, call and response is used, as "simplicity" is the solution for each of the "error[s]" and "clout[s]," making the decision to simplify one's life most effective. To further this point, juxtaposition shows the contrast between society's value of a good life and the reality of it, as a "chopping sea" is compared to "civilized life" (60). A chopping sea evokes images of violence and disaster, which is how Thoreau argues that an unsimplified life will similarly bring ruin. This comparison continues into an extended metaphor, detailing the "clouds and storms and quicksands" that could be avoided if one would remove the unnecessary "thousand-and-one items to be allowed for" (60). In this way, Thoreau shows that one will be saved from the overwhelming disasters of a complex life by taking out anything that is unnecessary. So, this passage emphasizes the principle of simplifying one's life through the use of repetition, juxtaposition, and extended metaphors.</p>
                <p>This passage spoke to me because, although I'm not a materialistic person, I tend to think about a "thousand-and-one" thoughts all at once. I want to focus on simplifying my thought process so that I can go through fewer and more important thoughts on their own. Modern society places a large emphasis on rushing through life to get to the next step, which I think has influenced my way of thinking, but it will be a good challenge to slow down and dig deeper into my thoughts. To do this, I plan to meditate every day in the early afternoon. I chose this time because I want it to interrupt my normal schedule, taking me away from the rush of planning ahead and getting things done, so that I can return with more focus and with more explored thoughts.</p>
                <hr>
            </div>
            <div class="analysis-block">
                <div class="panel panel-default quote">
                    <div class="panel-body">
                        "Yet I experienced sometimes that the most sweet and tender, the most innocent and encouraging society may be found in any natural object, even for the poor misanthrope and most melancholy man. There can be no very black melancholy to him who lives in the midst of Nature and has his senses still. There was never yet such a storm but it was Æolian music to a healthy and innocent ear. Nothing can rightly compel a simple and brave man to a vulgar sadness. While I enjoy the friendship of the seasons I trust that nothing can make life a burden to me. The gentle rain which waters my beans and keeps me in the house today is not drear and melancholy, but good for me too. Though it prevents my hoeing them, it is of far more worth than my hoeing. If it should continue so long as to cause the seeds to rot in the ground and destroy the potatoes in the low lands, it would still be good for the grass on the uplands, and, being good for the grass, it would be good for me. Sometimes, when I compare myself with other men, it seems as if I were more favored by the gods than they, beyond any deserts that I am conscious of; as if I had a warrant and surety at their hands which my fellows have not, and were especially guided and guarded. I do not flatter myself, but if it be possible they flatter me. I have never felt lonesome, or in the least oppressed by a sense of solitude, but once, and that was a few weeks after I came to the woods, when, for an hour, I doubted if the near neighborhood of man was not essential to a serene and healthy life. To be alone was something unpleasant. But I was at the same time conscious of a slight insanity in my mood, and seemed to foresee my recovery. In the midst of a gentle rain while these thoughts prevailed, I was suddenly sensible of such sweet and beneficent society in Nature, in the very pattering of the drops, and in every sound and sight around my house, an infinite and unaccountable friendliness all at once like an atmosphere sustaining me, as made the fancied advantages of human neighborhood insignificant, and I have never thought of them since. Every little pine needle expanded and swelled with sympathy and befriended me. I was so distinctly made aware of the presence of something kindred to me, even in scenes which we are accustomed to call wild and dreary, and also that the nearest of blood to me and humanest was not a person nor a villager, that I thought no place could ever be strange to me again." - Thoreau
                    </div>
                </div>
                <p>This passage uses juxtaposition, alliteration, and imagery to advocate for spending time with nature. First, Thoreau argues that "the most innocent and encouraging society may be found in any natural object, even in the poor misanthrope and most melancholy man," juxtaposing "innocent and encouraging society" with "the poor misanthrope and most melancholy man" (85). Here, this contrast between positive and negative words shows how powerful the fundamental human connection with nature his; no matter how sad or hostile one is, they can find comfort and beauty in nature, clearly encouraging readers to spend time with nature. In addition, alliteration and imagery are used in an anecdote describing nature's power on Thoreau. Imagery in the "pattering of the [rain]drops" draws readers into the tale, evoking sounds of the rain falling around them (86). The gentle noise helps one immediately think of nature in a kind, positive light. It also sets the scene for when he feels "every little pine needle...swelled with sympathy" (86). The alliteration in "swelled with sympathy" focuses the reader on nature's response to Thoreau himself, and the imagery in this statement helps the readers believe this deep connection. So, Thoreau uses these three techniques, juxtaposition, alliteration, and imagery, to show how powerful one's connection with nature is, encouraging readers to spend more time outdoors.</p>
                <p>I chose this passage because I agree that it is important to spend time outdoors; as Thoreau mentions in another passage, people often try to visit places where they feel a personal connection with nature, especially when given the opportunity to see phenomena like waterfalls, sunsets, and exotic animals. These journeys outside, however notable, are sparse, and I see this in my own life, especially because of cold weather and working inside. My goal is to appreciate the beauty of nature on a smaller scale, and find a deeper connection with nature. This way, I can find happiness in a new place, and become in touch with the world around me.</p>
                <hr>
            </div>
            <div class="analysis-block">
                <div class="panel panel-default quote">
                    <div class="panel-body">
                        "Man is timid and apologetic; he is no longer upright; he dares not say 'I think,' 'I am,' but quotes some saint or sage. He is ashamed before the blade of grass or the blowing rose. These roses under my window make no reference to former roses or to better ones; they are for what they are; they exist with God to-day. There is no time to them. There is simply the rose; it is perfect in every moment of its existence. Before a leaf-bud has burst, its whole life acts; in the full-blown flower there is no more; in the leafless root there is no less. Its nature is satisfied, and it satisfies nature, in all moments alike. But man postpones or remembers; he does not live in the present, but with reverted eye laments the past, or, heedless of the riches that surround him, stands on tiptoe to foresee the future. He cannot be happy and strong until he too lives with nature in the present, above time." - Emerson
                    </div>
                </div>
                <p>People often look to both the past and the future as being much better than the present, but by using repetition and parallelism, Ralph Waldo Emerson argues in Self Reliance that all of these states are perfect if one appreciates them. To show this, he first notes the timelessness of nature; plants do not think of other moments in time like humans, as "they are for what they are" (Emerson). The parallelism of this clause shows that one will not lose anything by only focusing on the present; like the "blade of grass or the blowing rose," one should just exist, and not worry about how to change themselves to fit a different point in time. In addition, he believes that "in the full-blown flower," a combination of the seemingly wonderful past and future, "there is no more; in the leafless root," the present, "there is no less." Here, the similar structure of these parts of the sentence mirror the true equality of the flower and the root, though they look different. Emerson goes on to say that the root's "nature is satisfied, and it satisfies nature," though it may not be seen as having the same value as the flower. This parallelism and repetition of "nature" and "satisfy" continues the balance between the root and flower.</p>
                <p>In modern society, there is always a focus on looking back at our "glory days," or thinking about how to make the future better. However, there is no strong emphasis on enjoying the present, and so even I forget to live in the moment. My solution for this is to meditate every day because it will force me to focus on what is happening in the present, and it is a practical, everyday solution. I think it is important to plan for the future but to not worry too much about it, because if one lives with this mentality forever, they will never be able to appreciate what they have, and I want to be able to enjoy my life as it happens.</p>
                <hr>
            </div>
            <div class="analysis-block">
                <div class="panel panel-default quote">
                    <div class="panel-body">
                        "Insist on yourself; never imitate. Your own gift you can present every moment with the cumulative force of a whole life's cultivation; but of the adopted talent of another, you have only an extemporaneous, half possession. That which each can do best, none but his Maker can teach him. No man yet knows what it is, nor can, till that person has exhibited it. Where is the master who could have taught Shakspeare? Where is the master who could have instructed Franklin, or Washington, or Bacon, or Newton? Every great man is a unique. The Scipionism of Scipio is precisely that part he could not borrow. Shakspeare will never be made by the study of Shakspeare. Do that which is assigned you, and you cannot hope too much or dare too much." - Emerson
                    </div>
                </div>
                <p>Here, Ralph Waldo Emerson advocates for everyone to follow what they are passionate about instead of trying to copy what another person is doing. He uses alliteration by promising that one's "own gift" can be presented with "the cumulative force of a whole life's cultivation" (Emerson). Here, "cumulative" and "cultivation" resonate with each other to emphasize the great power of one's own gift. He also alludes to the story of the Roman general Scipio, who was able to defeat Hannibal, considered to be one of the greatest military leaders in history. By mentioning Scipio and many famous intellectuals, he reinforces the idea that one cannot directly copy someone else and be great; instead, one must do "that which" he "can do best."</p>
                <p>This passage applies to high school, because there is a culture that encourages everyone to copy the best people in order to get into a high ranked college. So, many people are worried about doing things that everyone else is doing to comply with that culture, even if they are not interested in those things. However, it is important to explore one's passions and create a new path, so that eventually one can find what they love doing. From here, innovation and creativity can flourish. One way to apply this to everyday life is to continuously try new things, even if society does not deem them to be important. For me, this will involve exploring photography, an activity that I am interested in but have never pursued seriously before. I think this is a good way to explore something new, and if it turns out to be something I enjoy, I can work on it "with the cumulative force of a whole life's cultivation."</p>
            </div>
        </div>
    </div>
</div>

<h2 id="insights">Insights gained</h2>
<p>Overall, I'd say this project was a success. I was able to stick to my two goals, and I discovered that I really enjoy both meditation and photography. I will definitely keep doing both! I think I understand Transcendentalism better now after being able to experience it for myself after just reading about it.</p>
<p>In the <a href="#before">before section</a>, I mentioned how I was living a fast life and I didn't spend much time outside. Looking back, I think these two are related. When I was inside, I only focused on work and getting things done, but when I forced myself to go outside, I was able to focus on something completely different and take a step back from a busy schedule.</p>
<p>The meditation and photography encouraged introspection and awareness of both the self and surroundings. I think they worked to complement each other, and helped me slow down my life. I was happy to ensure that there was a block of time for things I enjoyed.</p>

<h2 id="more">More Transcendentalism</h2>
<p>These are some things that remind me of Transcendentalism, and were used throughout the project to fully immerse myself in the philosophy.</p>

<h3>Music</h3>
<p>I think Thoreau and Emerson would have been fans of ambient music because it's very calming and good for focusing on oneself. In addition, many songs feature sounds from nature. I listened to the "Deep Focus" playlist on Spotify.</p>
<iframe src="https://embed.spotify.com/?uri=http://open.spotify.com/user/spotify/playlist/2ujjMpFriZ2nayLmrD1Jgl" width="300" height="380" frameborder="0" allowtransparency="true"></iframe>

<?php include 'footer.php' ?>